version: 2.1
orbs:
  github-cli: circleci/github-cli@2.1.0

build_filter: &build_filter
  filters:
    tags:
      ignore: /^v\d+\.\d+\.\d+$/

release_filter: &release_filter
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v\d+\.\d+\.\d+$/

jobs:
  build-and-test:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run: make build
      - run: make test

  build-and-release:
    docker:
      - image: cimg/go:1.21
    parameters:
      goos:
        default: linux
        type: string
      goarch:
        default: amd64
        type: string
    environment:
      GOOS: << parameters.goos >>
      GOOARCH: << parameters.goarch >>
    steps:
      - checkout
      - run: make build
      - run: make release
      - persist_to_workspace:
          root: build
          paths:
            - bastion-web-proxy-*.tgz

  release-to-github:
    docker:
      - image: cimg/base:2023.09
    environment:
      GIT_TAG: << pipeline.git.tag >>
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - github-cli/setup
      - run:
          command: >
            gh release upload $GIT_TAG /tmp/workspace/bastion-web-proxy-*.tgz

workflows:
  version: 2
  build-workflow:
    jobs:
      - build-and-test:
          <<: *build_filter

  release-workflow:
    jobs:
      - build-and-test:
          <<: *release_filter

      - build-and-release:
          <<: *release_filter
          name: build-and-release (linux/amd64)
          goos: linux
          goarch: amd64
          requires:
            - build-and-test

      - build-and-release:
          <<: *release_filter
          name: build-and-release (darwin/amd64)
          goos: darwin
          goarch: amd64
          requires:
            - build-and-test

      - release-to-github:
          <<: *release_filter
          name: release-to-github
          context:
            - default
          requires:
            - build-and-release (linux/amd64)
            - build-and-release (darwin/amd64)
